[project]
name = "gtfs-de-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "evanmathew", email = "" }
]
requires-python = ">=3.14"
dependencies = [
    "confluent-kafka>=2.15.1",
    "dbt-core>=1.12.5",
    "dbt-duckdb>=1.11.0",
    "duckdb>=1.5.5",
    "gtfs-realtime-bindings>=2.2.0",
    "pandas>=3.0.6",
    "psycopg2-binary>=2.9.13",
    "pyarrow>=25.0.1",
    "pyiceberg>=0.12.0",
    "sqlalchemy>=2.0.54",
]

[project.scripts]
gtfs-de-pipeline = "gtfs_de_pipeline:main"

[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"
